FROM redmine
#RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev

WORKDIR /usr/src/redmine

COPY redmine_agile /usr/src/redmine/plugins/redmine_agile
RUN bundle install --no-deployment
